### ISSUE TITLE
Add Prostate158 model

### ISSUE THREAD

**Issue by fedorov** [MHubAI/models#64]
@LennyN95 @denbonte - we would like to add Prostate158 zonal segmentation model. @ccosmin97 is happy to work on this, although he would definitely appreciate help from the original developer @kbressem (perhaps this is anyway consistent with @hugoaerts desire to have more AIM-Harvard models in MHub).

Can we discuss steps/timeline/missing features (hopefully none!) here?

**Comment by LennyN95** [comment]
Hey Andrey, 
This is about the monai model? I'm working on a MonaiBundleRunner (similar to the NNUnetRunner) to bootstrap the deployment of Monai models. However, no need to wait for this if you're under timely pressure ;)

@ccosmin97 Were you able to run the model? If yes, deployment in MHub should be quite straightforward. We can set up a meeting this or the upcoming week and I can guide you through the steps (or you can already start based on our documentation, I'll link the relevant articles below). If not, then I suggest we arrange a meeting including @kbressem so he can help with the setup.

Good starting point:
https://github.com/MHubAI/documentation/blob/main/documentation/mhub_models/model_folder_structure.md

**Comment by kbressem** [comment]
Happy to help with the model. @FaresAlMohamad fixed the orientation issue in the meantime, so the model should work well.

**Comment by LennyN95** [comment]
Any progress here @ccosmin97, @kbressem, @fedorov?

**Comment by ccosmin97** [comment]
@LennyN95 @kbressem @fedorov Sorry for the late update, I will get on the implementation. A discussion about the implementation of prostate158 model would be useful, whenever you can next week or later. Thank you!

I was able to run the prostate158 model in my analysis through Google Colab with no issues. I guess the main question is how to implement a MonaiBundleRunner in MHub.

**Comment by LennyN95** [comment]
Let's discuss in a bit @ccosmin97. For now, I wouldn't focus on a generic MonaiBundleRunner, let's implement the model with a from-scratch Module. Then once we've a couple Monai-based models implemented and I see enough synergy and boilerplate code, I'll wrap it up in a MonaiBundleRunner to ease the process for future contributions ;)
