### ISSUE TITLE
Per @vkt1414, the version in mhub base image is from 2018!

### ISSUE THREAD

**Issue by LennyN95** [MHubAI/models#72]
Per @vkt1414, the version in mhub base image is from 2018!

We should get the latest stable release from https://github.com/rordenlab/dcm2niix/releases instead.

_Ursprünglich gepostet von @fedorov in https://github.com/MHubAI/mhubio/issues/2_

**Comment by denbonte** [comment]
I tried running a container from the Ubuntu 20.04 LTS image, installing just `wget`, `python3`, and `python3-pip` - and the binaries for `s5cmd` and `dcm2niix` (from GitHub releases).

This seems to work fine. From the checks and in @fedorov's opinion as well, the binary for `dcm2niix` should be self-contained. We should be good to go - but it's worth looking into having a script to pull from github a specific package once given a version or a tag.

For instance, something like `install_dcm2niix_git` that accepts a release tag as an input and then pulls the Linux binaries for that release tag, unzips/untars the archive, and moves it to `/usr/bin/`. If not specified, we could make this pull the most recent release (excluding latest, if present - like in `dcmqi`'s case).

>Ursprünglich gepostet von @fedorov in https://github.com/MHubAI/mhubio/issues/2

Nice.

**Comment by LennyN95** [comment]
Base image has already been updated to ubuntu 20.04.
