### ISSUE TITLE
Update images for model bamf_nnunet_mr_liver

### ISSUE THREAD

**Issue by jithenece** [MHubAI/models#95]
The sample screenshots for the below test case attached as zip file. Please update this under [bamf_nnunet_mr_liver](https://mhub.ai/models/bamf_nnunet_mr_liver) page

[Archive.zip](https://github.com/user-attachments/files/16625486/Archive.zip)

**Comment by jithenece** [comment]
could you update this please?

**Comment by LennyN95** [comment]
Done, thx for the reminder!
